# The "ui" section defines where you want Node.js to run/respond. It often is a *localhost* (non-public) URL, especially if you are using a Proxy.
# In this example, we are setting up our UI to just use localhost, port 4000.
# This is a common setup for when you want to use Apache or Nginx to handle HTTPS and proxy requests to Node on port 4000
ui:
  ssl: false  
  host: localhost
  port: 4000
  nameSpace: /
 
# The REST settings MUST correspond to the primary/public URL of the backend. Usually, this means they must be kept in sync
# with the value of "dspace.server.url" in the backend's local.cfg
rest:
  ssl: true
  host: ub-fisdev-backend.ub.tu-freiberg.de
  port: 443
  nameSpace: /server

defaultLanguage: en

# Languages. DSpace Angular holds a message catalog for each of the following languages.
# When set to active, users will be able to switch to the use of this language in the user interface.
# All out of the box language packs may be found in the ./src/assets/i18n/ directory
languages:
  - code: en
    label: English
    active: true
  - code: de
    label: Deutsch
    active: true

# enable theme
themes:
  - name: 'tubaf'
    headTags:
    - tagName: link
      attributes:
        rel: icon
        href: assets/tubaf/images/favicons/favicon.ico
        sizes: any
    - tagName: link
      attributes:
        rel: icon
        href: assets/tubaf/images/favicons/favicon.svg
        type: image/svg+xml
    - tagName: link
      attributes:
        rel: apple-touch-icon
        href: assets/tubaf/images/favicons/apple-touch-icon.png
    - tagName: link
      attributes:
        rel: manifest
        href: assets/tubaf/images/favicons/manifest.webmanifest


# try some Layout from example.yml
#crisLayout:
#  urn:
#    - name: doi
#      baseUrl: "https://doi.org/"
#    - name: hdl
#      baseUrl: "https://hdl.handle.net/"
#    - name: scopus
#      baseUrl: "https://www.scopus.com/authid/detail.uri?authorId="
#    - name: researcherid
#      baseUrl: "http://www.researcherid.com/rid/"
#    - name: mailto
#      baseUrl: "mailto:"
#  crisRef:
#    - entityType: PRIVATE
#      entityStyle:
#        "dc.contributor.author":
#          icon: fa fa-user
#          style: text-muted
#    - entityType: DEFAULT
#      entityStyle:
#        default:
#          icon: fa fa-user
#          style: text-info
#    - entityType: PERSON
#      entityStyle:
#        person:
#          icon: fa fa-user
#          style: text-success
#        personStaff:
#          icon: fa fa-user
#          style: text-danger
#        default:
#          icon: fa fa-user
#          style: text-info
#    - entityType: ORGUNIT
#      entityStyle:
#        default:
#          icon: fa fa-university
#          style: text-success
#    - entityType: PROJECT
#      entityStyle:
#        default:
#          icon: fas fa-project-diagram
#          style: text-success
#  crisRefStyleMetadata: "cris.entity.style"
#  itemPage:
#    OrgUnit:
#      orientation: vertical
#    Project:
#      orientation: vertical
#    default:
#      orientation: horizontal
#  metadataBox:
#    defaultMetadataLabelColStyle: "col-3"
#    defaultMetadataValueColStyle: "col-9"
